### ISSUE TITLE
from ts import JNIClient

### ISSUE THREAD

**Issue by jonbaer** [vwxyzjn/gym-microrts#1]
Getting raise ImportError("Unable to find java class '%s'"%jname)
ImportError: Unable to find java class 'tests.JNIClient' ...

Do I need to use your fork of microrts?  The README points to use the official distro.

**Comment by vwxyzjn** [comment]
Hi,

Did you download the microrts jar file?

```
$ rm ~/microrts -fR && mkdir ~/microrts && \
wget -O ~/microrts/microrts.zip http://microrts.s3.amazonaws.com/microrts/artifacts/202001310341.microrts.zip && \
unzip ~/microrts/microrts.zip -d ~/microrts/ && \
rm ~/microrts/microrts.zip
```

**Comment by jonbaer** [comment]
It looks like I need your client @ https://github.com/vwxyzjn/microrts/blob/master/src/tests/JNIClient.java

**Comment by vwxyzjn** [comment]
That file is included in the jar file. Did you follow the instructions I posted above

**Comment by jonbaer** [comment]
Yes, I think I fixed it, it was a JPype issue, but the only thing is I can't seem to render the env, the hello_world will run ...

~/microrts/maps/4x4/baseTwoWorkers4x4.xml
[Lai.rewardfunction.RewardFunctionInterface;@13221655 

Same w/ monitor (no video)

One thing I did notice was that running jtest is error because the JNIClient is looking for an array of reward function interfaces.

TypeError: No matching overloads found for constructor tests.JNIClient(ai.rewardfunction.SimpleEvaluationRewardFunction,str,str,int), options are:
	public tests.JNIClient(ai.rewardfunction.RewardFunctionInterface[],java.lang.String,java.lang.String,int) throws java.lang.Exception
	public tests.JNIClient(ai.rewardfunction.RewardFunctionInterface[],java.lang.String,java.lang.String) throws java.lang.Exception

**Comment by vwxyzjn** [comment]
Try grabbing a new version here http://microrts.s3-website-us-east-1.amazonaws.com/microrts/artifacts/

**Comment by jonbaer** [comment]
No luck, forgot to mention on OSX Catalina, the demo looks like it's playing out on Konsole/Linux.  A different python lib works (https://github.com/Bam4d/python-microRTS.git) - if anyone else has gotten the gym env running on OSX please chime in.

**Comment by vwxyzjn** [comment]
So when you call the render function, nothing appears?

**Comment by vwxyzjn** [comment]
@jonbaer Could you double check if you installed the full JRE? Once I only installed 

jre-openjdk-headless and I couldn't render the game. Maybe that was the issue.

![image](https://user-images.githubusercontent.com/5555347/74621452-0c3c7400-510b-11ea-9f2f-159a6a203111.png)

The error regarding the `jtest.py` is expected since that was just a file for testing purposes. Thank you for being one of my first users, I will try to address your problems as much as I could.

**Comment by jonbaer** [comment]
I just want to make sure, when I run hello_world I should automatically get the Game State Visualizer on it's own or do I need to be running microrts in the background for the VM/JNIClient connection?  It looks like self.client.render() does what it is suppose to.  I also added a small pause time.sleep(0.1) after the render() as some suggested for running some envs but still no luck.

**Comment by vwxyzjn** [comment]
So env.render() should automatically give you the visualizer.

Costa

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vwxyzjn** [comment]
https://youtu.be/9gm21uDZxls It should look something like this.

**Comment by jonbaer** [comment]
I think I have figured out part of my issue, it's has to do w/ the way Jpype on OSX is working, it is not picking up the right VM, ie: startJVM(getDefaultJVMPath()) ... but there is also something which seems to block Swing app (microRTS) from running on my particular python setup.  Sounds like I might have to tweak both my python and JVM settings, if I come across any good combo will post back here.

**Comment by vwxyzjn** [comment]
Sounds good. Please keep me posted.

**Comment by Thrameos** [comment]
@jonbaer Do you have a patch for OSX getDefaultJVMPath()?  It isn't something that I can replicate locally and would be nice to have fixed in the 0.8.0 release.

**Comment by vwxyzjn** [comment]
@Thrameos mad respect for your tracking down issues!

**Comment by vwxyzjn** [comment]
@Thrameos do you have a donation page?

**Comment by Thrameos** [comment]
Nope.  My job requires an ethics form that prevents me from accepting any type of donation.  But if you want to help donate a patch, correct my documentation,  or just participate in putting wish requests for future features it is always appreciated.  I always scan all the open issues when I am doing a major release and when I see a mention I just track it down.  If I do someday JPype will be a real boy and reach the big 1.0.

**Comment by jonbaer** [comment]
I did not but if it helps this is exactly where it will fail (out of box) on gym-microrts running hello_world ...

File "/Users/jonbaer/Library/Python/3.7/lib/python/site-packages/jpype/imports.py", line 344, in create_module
    return getattr(base, parts[-1])
AttributeError: module 'ts' has no attribute 'JNIClient'

So it is something around # Support of inner classes

**Comment by vwxyzjn** [comment]
@jonbaer thanks for testing. The `ts` module is registered by this line https://github.com/vwxyzjn/gym-microrts/blob/e9d4a2c4852502c4b62e66692a41231f52104f83/gym_microrts/envs/base_env.py#L46. If it doesn’t work, did you try downloading the latest Jpype and microrts jar releases?

**Comment by jonbaer** [comment]
Yes I have the latest and the following debug OK ...

print(jpype.getDefaultJVMPath())
print(jpype.getClassPath())

The problem seems to be that registerDomain("ts", alias="tests") doesn't seem to do the right thing if I see:

File "jtest.py", line 17, in <module>
    from ts import JNIClient
ImportError: cannot import name 'JNIClient' from 'ts' (/Users/jonbaer/Library/Python/3.7/lib/python/site-packages/ts/__init__.py)

**Comment by vwxyzjn** [comment]
![image](https://user-images.githubusercontent.com/5555347/82527376-4cddcc00-9b04-11ea-8bac-6356e7e430b4.png)

I just tested and it wasn't a problem for me. Well can you import from the `ai` package? Namely, do  you have an error when running `from ai.rewardfunction import ResourceGatherRewardFunction`?

**Comment by jonbaer** [comment]
On OSX? I think on Linux there is no problems w/ registerDomain, it seems to be some security issue w/ classpath setting specific to OSX + using JNI.  I seriously would probably not worry about this issue on your end (in fact this ticket could be closed because in theory w/ this RL case in general it should be run on the Linux/GPU side), I don't know if there have been OSX/Jpype issues in the past but really this should be vetted w/ another OSX developer so it's not just my setup that is not working right.  (If you find another Catalina user I would gladly exchange notes).

**Comment by Thrameos** [comment]
There was a code change in JPype recently that may be affecting this.   We recently switched to using a new helper class that automatically finds domains so that they can be picked up.   The idea is pretty simple.  Whenever a user calls for a domain lookup we ask the classpath for any occurrences of a jar with the required path and create it.

```import jpype
from jpype.types import *
import jpype.imports
jpype.startJVM()
import java
print(java.lang.System.getProperty('java.class.path'))

# Access the JPype internal resource
#  In this case we will get ahold of query interface for packages.
jpkg = JClass('org.jpype.pkg.JPypePackageManager')

print(jpkg.isPackage("java"))
print(jpkg.isPackage("ts"))
import ts
# See no register is required
```

The problem likely is that with the new package system the alias command is no longer being respected.  (I didn't have a test for it, so it didn't get checked.)  I will make a ticket in JPype and verify that alias will continue to work going forward.

In addition, the most common reason for a failed JPype import is a conflicting Python package.   You have to be careful not to name any Java packages with a name that may hit an existing Python package.  The Java package extensions have very low priority.   So any package called "ts", a directory called "ts", or a file called "ts.py" will likely override the import of a "ts" package.     Thus if you don't want to have some rather horrible to track down site specific problems, be careful when naming packages.

**Comment by Thrameos** [comment]
I have complete a PR which should restore the alias behavior.   Hopefully this corrects this issue.

**Comment by jonbaer** [comment]
Wait so (in reference to your example code) how would you actually append a new jar to the classpath? Would this be something to do before or after (or during) your call to startJVM()?  I tried both:

jpype.startJVM((jpype.getDefaultJVMPath(), '-ea', '-Djava.class.path=/Users/jonbaer/microrts/microrts.jar'))

jpype.addClassPath("/Users/jonbaer/microrts/microrts.jar")

And also un-jarred to a flat directory.  "ts" is actually inside this .jar, the idea of no register or alias is good but I have the feeling if like you said, there will be plenty of naming conflicts to workaround.

**Comment by Thrameos** [comment]
The syntax is ``jpype.startJVM( jvmpath, *args, classpath=_default)``  where the jvmpath and args are both optional. If the classpath keyword is specified than it governs or a -Djava.class.path appears, otherwise it will use jpype.getClassPath().   

So the following are acceptable:

- Start using a specific jar for the classpath, default JVM.
```
jpype.startJVM(classpath='/Users/jonbaer/microrts/microrts.jar')
```

- Start using a specific jar for the classpath with an argument to the JVM, default JVM.

```
jpype.startJVM(classpath='/Users/jonbaer/microrts/*')
```

- Start using a specific jvm with an argument, and a specific jar, default JVM.   This is triggered if the first argument does not start with a dash.

```
jpype.startJVM("/sys/opt/jdk8/","-ea",classpath='/Users/jonbaer/microrts/microrts.jar')
```

- Start using 2 options, with a jar and all jars from a folder,  default JVM.  This is triggered by having a list for the class path.

```
jpype.startJVM("-ea", "-Xm256M",classpath=['/Users/jonbaer/microrts/microrts.jar', '/Users/jonbaer/microrts/libs/*'])
```

- MATLAB STYLE Start using 2 options, with a specific jar and all jars from a folder.

```
jpype.addClassPath('/Users/jonbaer/microrts/microrts.jar')
jpype.addClassPath('/Users/jonbaer/microrts/libs/*')
jpype.startJVM(jpype.getDefaultJVMPath(),"-ea", "-Xm256M")
```

 - 0.6 LEGACY STYLE This one is error prone as people often get the callpath argument wrong and because ignore unrecognized was set to True it causes lots of problems.   I would not recommend this currently as the likelihood of errors is high.

```
jpype.startJVM(jpype.getDefaultJVMPath(), "-ea", "-Xm256M", "-Djava.class.path=/Users/jonbaer/microrts/microrts.jar")
```

**Comment by Thrameos** [comment]
Oh I missed part of the question.   Classpath can be added prior to start (MATLAB style), or during the startup.    

Adding jars after is doable, but requires work so I don't usually recommend it.   The proceed for adding a jar after starting the JVM is to create a URLClassLoader in Java with the jar file and then adding that classloader to the search tree or manually loading the classes using JClass.  This option is not tested so may have bugs.

There are added complexities if you have a jar with a native component as you also need to libpath to be installed as well as the class path.  Mostly a problem for JDBC users.

**Comment by vwxyzjn** [comment]
For a lack of response, closing this issue for now.
